FROM debian:bookworm-slim

RUN apt-get update && apt-get install -y apache2 && \
    a2enmod proxy proxy_http rewrite headers && \
    apt-get clean

RUN usermod -u 1000 www-data && groupmod -g 1000 www-data

EXPOSE 80
CMD ["apache2ctl", "-D", "FOREGROUND"]