FROM node:22-alpine AS base
WORKDIR /app
COPY backend/package*.json ./

FROM base AS development
RUN npm install -g nodemon
RUN npm install
COPY backend/ .
EXPOSE 3000
CMD ["npm", "run", "dev"]

FROM base AS production
RUN npm ci --omit=dev
COPY backend/ .
EXPOSE 3000
CMD ["npm", "run", "start"]